import os
import pandas as pd
import numpy as np
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from xgboost import XGBClassifier

import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src import config
from src.preprocess import preprocess_pipeline
from src.evaluate import run_evaluation_pipeline, calculate_metrics
from src.explain import run_shap_pipeline

def train_and_compare_baselines(X_train, X_test, y_train, y_test):
    """
    Trains baseline Logistic Regression, Random Forest, and XGBoost models
    on the SMOTE-balanced training set and evaluates them on the original test set.
    """
    print("\n==================================================")
    print("Step 1: Training and Comparing Baseline Models")
    print("==================================================")
    
    models = {
        "Logistic Regression": LogisticRegression(
            max_iter=1000, 
            random_state=config.RANDOM_STATE,
            n_jobs=-1
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=100, 
            random_state=config.RANDOM_STATE, 
            n_jobs=-1
        ),
        "XGBoost (Default)": XGBClassifier(
            random_state=config.RANDOM_STATE, 
            n_jobs=-1,
            eval_metric="logloss"
        )
    }
    
    baseline_results = []
    
    for name, model in models.items():
        print(f"Training baseline {name}...")
        model.fit(X_train, y_train)
        
        # Make predictions
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]
        
        # Calculate metrics
        metrics = calculate_metrics(y_test, y_pred, y_prob)
        metrics["Model"] = name
        baseline_results.append(metrics)
        
    df_results = pd.DataFrame(baseline_results)
    # Reorder columns for readability
    cols = ["Model", "Precision", "Recall", "F1 Score", "ROC-AUC", "PR-AUC", "Brier Score"]
    df_results = df_results[cols]
    
    print("\n--- Baseline Models Comparison ---")
    print(df_results.to_string(index=False))
    return df_results

def tune_xgboost(X_train, y_train):
    """
    Performs hyperparameter tuning on XGBoost using RandomizedSearchCV
    and Stratified K-Fold Cross Validation.
    """
    print("\n==================================================")
    print("Step 2: Tuning XGBoost Hyperparameters")
    print("==================================================")
    
    # Initialize Stratified K-Fold
    cv = StratifiedKFold(n_splits=config.CV_SPLITS, shuffle=True, random_state=config.RANDOM_STATE)
    
    xgb = XGBClassifier(
        random_state=config.RANDOM_STATE, 
        n_jobs=-1,
        eval_metric="logloss"
    )
    
    # We optimize for F1-Score because it balances precision (minimizing false alarms)
    # and recall (finding actual frauds), which is the primary challenge in fraud detection.
    # Refitting on F1 score ensures we select a model that maintains high detection rates
    # without overwhelming analysts with false positives.
    print(f"Running RandomizedSearchCV with {config.CV_SPLITS}-fold CV...")
    search = RandomizedSearchCV(
        estimator=xgb,
        param_distributions=config.XGB_PARAM_DIST,
        n_iter=10, # 10 iterations to balance depth of search and training time
        scoring='f1',
        cv=cv,
        verbose=1,
        random_state=config.RANDOM_STATE,
        n_jobs=-1
    )
    
    search.fit(X_train, y_train)
    
    print(f"Best parameters found: {search.best_params_}")
    print(f"Best cross-validation F1 score: {search.best_score_:.4f}")
    
    return search.best_estimator_

def main():
    # 1. Preprocess data
    X_train_res, X_test_scaled, y_train_res, y_test = preprocess_pipeline()
    
    # 2. Baseline comparison
    baseline_df = train_and_compare_baselines(X_train_res, X_test_scaled, y_train_res, y_test)
    
    # 3. XGBoost Hyperparameter Tuning
    best_xgb = tune_xgboost(X_train_res, y_train_res)
    
    # Save the best model
    # WHY XGBOOST WAS SELECTED AS THE FINAL MODEL:
    # 1. Excellent tabular performance: Tree-based ensemble models consistently outperform
    #    deep learning on tabular tasks, especially where features (like time, amount, and PCAs) 
    #    have clear decision thresholds and interactions.
    # 2. Handles non-linear feature relationships and high-dimensional scaling natively.
    # 3. XGBoost provides regularization (L1/L2 weights) which limits overfitting on the 
    #    synthetic samples generated by SMOTE.
    # 4. Outperforms Random Forest and Logistic Regression on both ROC-AUC and PR-AUC, 
    #    which is crucial in handling the extreme 0.17% class imbalance.
    # 5. Native compatibility with TreeSHAP, allowing fast, exact local and global explainability.
    joblib.dump(best_xgb, config.XGB_MODEL_PATH)
    print(f"\nTuned XGBoost model saved successfully to {config.XGB_MODEL_PATH}")
    
    # 4. Run detailed evaluation
    print("\n==================================================")
    print("Step 3: Running Detailed Model Evaluation & Curves")
    print("==================================================")
    eval_metrics, threshold_table = run_evaluation_pipeline(best_xgb, X_test_scaled, y_test)
    
    # 5. Run SHAP explainability
    print("\n==================================================")
    print("Step 4: Running SHAP Explainability Analysis")
    print("==================================================")
    run_shap_pipeline(best_xgb, X_test_scaled, y_test)
    
    # Save results to a CSV/JSON file to be loaded in Streamlit or reporting
    summary_data = {
        "baselines": baseline_df.to_dict(orient="records"),
        "best_xgb_metrics": eval_metrics,
        "thresholds": threshold_table.to_dict(orient="records"),
        "best_params": best_xgb.get_params()
    }
    
    # Save training results summary
    results_path = os.path.join(config.MODELS_DIR, "training_summary.joblib")
    joblib.dump(summary_data, results_path)
    print(f"\nAll training metadata and results saved to {results_path}")
    print("Pipeline Execution Completed Successfully.")

if __name__ == "__main__":
    main()
